Fix: Fixed autogenerated description
springwolf/springwolf-core pull request #189
Opened 2023-05-31 07:32 UTC by ctasada

When defining an `@AsyncOperation` description like in

```
@AsyncOperation(
    channelName = "channel-name",
    description = "My channel description")
```

The generated AsyncAPI schema was always showing `Auto-generated description`

2023-06-02 16:06 UTC, sam0r040 requested changes
Thanks a lot for your contribution, I just made a suggestion on how to resolve the FIXME comment.

2023-06-02 16:06 UTC, sam0r040 requested changes
Thanks a lot for your contribution, I just made a suggestion on how to resolve the FIXME comment.

2023-06-03 08:55 UTC, ctasada commented on springwolf-core/src/main/java/io/github/stavshamir/springwolf/asyncapi/scanners/channels/operationdata/AbstractOperationDataScanner.java
>                  .description(operationData.getDescription())
@sam0r040 I agree that we need to change it. If I remove the line, the message description becomes `null`

I think the proper solution here is that we need to obtain the value from the `@Schema(description = "Message/Schema description goes here")`

I can remove the line and "fix" all the tests (validating the description is `null`) or leave it like it's now (the bug was already there). Next week I can work in another PR to address this issue.

What do you prefer?

2023-06-04 09:49 UTC, timonback commented on springwolf-core/src/main/java/io/github/stavshamir/springwolf/asyncapi/scanners/channels/operationdata/AbstractOperationDataScanner.java
>                  .description(operationData.getDescription())
As a first step, I am also fine with removing the line and letting the field be implicitly `null`, which isn't rendered into the final document.

I like the idea to use the Schema annotation as a source. Maybe we can utilize it through the SchemaService?

But probably better to fix the description first, and put the feature of the message description in a new PR.

2023-06-04 09:50 UTC, timonback commented
@ctasada Is there anything anything else you like to see being included in the next release?

2023-06-05 13:04 UTC, ctasada commented on springwolf-core/src/main/java/io/github/stavshamir/springwolf/asyncapi/scanners/channels/operationdata/AbstractOperationDataScanner.java
>                  .description(operationData.getDescription())
@sam0r040 @timonback I will update the PR removing the line then.

2023-06-05 13:05 UTC, ctasada commented
> @ctasada Is there anything anything else you like to see being included in the next release?

Nothing urgent. If we can get another release done in 2-4 weeks I think I'm good 😉

2023-06-05 18:50 UTC, timonback approved these changes

2023-06-05 18:50 UTC, merged