Ability of specifying base package for configuration beans
springwolf/springwolf-core pull request #63
Opened 2022-05-06 09:36 UTC by Stmated

Ability of specifying base package for configuration beans, so components that are registered inside @Configuration can be found. This is because some projects simply do not use the `@Component` annotation, instead manually wire the beans.

In a way I think this overcomplicates things, and it would almost be easier to give ANT path pattern for which classes to search, and the code would just search all the methods of all the classes that match that pattern, with no regard to any class-level annotations at all.

Probable issues with this PR:
* It removes `@Configuration` from being matched in the regular base package scanning. So if a user has a `@KafkaListener` inside a `@Configuration` class, it would not be found.

2022-05-06 09:41 UTC, Stmated commented
It would probably also be better to change the docket to take a `ComponentScanner` instance instead of specifying the `basePackage`, so it is decoupled and you can give a custom `ComponentScanner` that works completely different depending on need. Like not wanting any scanning at all, and just giving your classes manually.

2022-05-06 10:05 UTC, stavshamir commented
Hi @Stmated , thanks for the PR! This does sound like a relevant use case that should be supported. 
I will look into it soon, in the meanwhile please merge from master as I just fixed a failing test.

2022-05-07 11:16 UTC, stavshamir commented on springwolf-core/src/main/java/io/github/stavshamir/springwolf/configuration/AsyncApiDocket.java
>      private String basePackage;
I think we should make the comments more clear, as `basePackage` and `configurationBasePackage` are very similar and may be confusing. 

I think this should change to: 
```java
/**
 * The base package to scan for listeners which are declared inside a class annotated with @Component or @Service.
*/
```

2022-05-07 11:21 UTC, stavshamir commented on springwolf-core/src/main/java/io/github/stavshamir/springwolf/configuration/AsyncApiDocket.java
> +    private String configurationBasePackage;
Like they comment above, I think this comment should be more specific:
```java
/**
* The base package to scan for @Configuration classes that contain beans that contain listeners. 
* Set this property if your listeners are declared in a class that is not annotated with @Component or @Service,
* and are declared in a class which is instantiated in a @Bean method in a @Configuration class.
*/
```

2022-05-07 11:40 UTC, stavshamir requested changes
@Stmated, that's a great contribution, well thought out and useful. I also appreciate providing new unit tests :) I have a few comments that I would like you to check and after the required changes I would gladly merge this!

2022-05-07 11:40 UTC, stavshamir commented on springwolf-core/src/main/java/io/github/stavshamir/springwolf/asyncapi/scanners/components/ComponentsScanner.java
> +    default Set<Class<?>> scanForComponents(String basePackage) {
Let's remove the argument completely form `scanForComponents` and leave it without arguments. Then we can also remove the `AsyncAciDocket` wirings from `AbstractChannelScanner` etc. and have `DefaultComponentScanner` ue the docket directly.

2022-05-07 11:40 UTC, stavshamir commented on springwolf-core/src/main/java/io/github/stavshamir/springwolf/asyncapi/scanners/components/DefaultComponentsScanner.java
Wire the `AsyncApiDocket` here instead of in `AbstrctChannelScanner`, `AbstractMethodLevelListener` and `ClassLevelKafkaListenerScanner`.

2022-05-07 11:40 UTC, stavshamir commented on springwolf-core/src/main/java/io/github/stavshamir/springwolf/asyncapi/scanners/components/DefaultComponentsScanner.java
> +            log.debug("Scanning for component classes in configuration package {}, filtered by beans in {}", configurationBasePackage, basePackage);
I think the filtering part is going to be too confusing - if the user want to scan based on beans in a configuration class, let it scan all the beans. Let's remove the filtering logic.

2022-05-07 11:40 UTC, stavshamir commented on springwolf-core/src/main/java/io/github/stavshamir/springwolf/asyncapi/scanners/components/DefaultComponentsScanner.java
> +        provider.addExcludeFilter(new AnnotationTypeFilter(Configuration.class));
Why should we exclude `@Configuration`?

2022-05-07 11:40 UTC, stavshamir commented on springwolf-core/src/main/java/io/github/stavshamir/springwolf/asyncapi/scanners/components/DefaultComponentsScanner.java
> +                        final String beanPackage = returnType.getPackage().getName();
As mentioned above, I think this would be too confusing, let's remove the package filtering logic here.

2022-05-07 11:40 UTC, stavshamir commented
@Stmated, that's a great contribution, well thought out and useful. I also appreciate providing new unit tests :) I have a few comments that I would like you to check and after the required changes I would gladly merge this!

2022-05-13 07:39 UTC, pontus-eliason commented
I did the changes noted in this PR, but also did a few extra things (which you might disagree with, who knows):

* Changed so `AsyncApiDocket` takes a `ComponentsScanner` directly, but backwards compatible to previous basePackage way.
* Added a `ApplicationContextComponentsScanner` which searches the bean registry. What's good about it: Can find beans given by external libraries and by a `FactoryBean`.
* Separated the different `ComponentsScanners` into what they do, and created a default `DefaultClassPathComponentsScanner` that searches for `@Component` and `@Configuration` + `@Bean` annotations.

I did not make any changes to documentation, since it all works like it did previously, just with an option to swap the scanner if want to.

2022-05-13 22:04 UTC, Stmated commented
And that ^ was me. Having multiple accounts is a hassle.

2022-05-22 18:33 UTC, stavshamir commented
Sorry for the long time it took me to review! 
Wow, that's a **very** impressive contribution. Thanks a lot. I will merge this now (the build is failing on some java doc stuff, I suspect it's related to lombok - I won't bother you with fixing that, I can do it myself).

Since this is a big amount of content added to the library, that would be great if we could also document it, so if you are looking for further contributions, I'm opening an issue in the project documentation site for this additions.

You are also welcome to the discord server that's starting to attract some action, and please add me on linkedin (https://www.linkedin.com/in/stavshamir/).

Cheers!

2022-05-22 18:35 UTC, merged